truncate events_count_by_sensor ; TRUNCATE device_location ; TRUNCATE online_users ;TRUNCATE events_count_by_device ;TRUNCATE online_devices ;TRUNCATE sensor_events ;TRUNCATE sensors_by_device ;


SELECT * from events_count_by_sensor ; SELECT * from device_location ;SELECT * from online_users ;SELECT * from events_count_by_device ;SELECT * from online_devices ;select * from sensor_events ; select * from sensors_by_device ;
